[workspace]
resolver = "3"
members = [
  "broto",
  "broto-derive"
]

default-members = [
    "broto",
    "broto-derive"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/nyanzebra/broto"

[workspace.dependencies]
futures-io = { version = "0.3" }
futures-util = { version = "0.3" }
proc-macro2 = "1"
quote = "1"
syn = { version = "2" }
thiserror = "2"
